# 服务器配置
server:
  port: 5050

spring:
  # MySQL连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingyi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    
  # Json返回格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
#  resources:
#    static-locations: classpath:/static/

      
# mapper配置
mybatis:
  mapper-locations: classpath*:com/seglino/jingyi/**/mapper/*Mapper.xml
  type-aliases-package: com.seglino.jingyi.**.pojo
  
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
    
# 日志配置
logging:
  level:
    root: info
#    com.seglino.jingyi.user.dao: debug
  file: ./logs/webapi.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'