server:
  port: 5050
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingyi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss 
    time-zone: GMT+8 
    serialization:
      write-dates-as-timestamps: false
 
mybatis:
  mapper-locations: classpath*:com/seglino/jingyi/**/mapper/*.xml
  type-aliases-package: com.seglino.jingyi.*.pojo